import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>VisualSource</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     
      <h2>VisualSource</h2>
      <hr/>
      <div className={styles.message}>
        The new site is sill under construction, come back later to see it in action
      </div>

    </div>
  )
}

export default Home
